import json
from pathlib import Path
from datetime import datetime, timezone
from autotrader.llm import record_usage
base=Path('artifacts')
opp=json.loads((base/'opportunities.json').read_text()); macro=json.loads((base/'macro.json').read_text()); state=json.loads((base/'state.json').read_text())
events=[json.loads(x) for x in (base/'events.jsonl').read_text().splitlines() if x.strip()]
onchain=[json.loads(x) for x in (base/'onchain.jsonl').read_text().splitlines() if x.strip()]
movers=json.loads((base/'movers.json').read_text()); top=opp['opportunities']['opportunities'][:3]; now=datetime.now(timezone.utc).isoformat()
analyses={'BNBUSDT':'信号0.75，但量比0.09极度萎缩、横盘且逆BTC trend_down，无量价确认，非A级执行机会。','LINKUSDT':'回踩EMA50约-0.41 ATR、RSI42，但量比0.24、24小时-0.57%，强度0.64低于阈值，等待放量和RSI上穿45。','NEOUSDT':'RSI27.3超卖但量比0，无止跌证据；等待量比>1、RSI回到30上方和结构确认。'}
log={'time':now,'opportunities_top':[{'symbol':x['symbol'],'price':x['price'],'rating':'关注' if (x.get('best') or {}).get('strength',0)>=0.7 else '观察','trend':x['trend'],'rsi14':x['rsi14'],'volume_ratio':x['volume_ratio'],'change_24h_pct':x['change_24h_pct'],'signal':x.get('best'),'analysis':analyses[x['symbol']]} for x in top],'event_impact':{'latest_A':'最近10条中A级事件占多数；Coldcard漏洞/被盗及持续利用叙事短线偏空，持续性取决于是否继续利用及被盗BTC是否移动。ETF流入、稳定币监管合作、支付牌照为中期对冲。事件impact=unknown，标题不证明价格因果。','a_events_reviewed':sum(e.get('grade')=='A' for e in events[-10:])},'resonance':{'technical':'BTC 64107低于EMA20 64153和EMA50 64190，trend_down、RSI41.8、量比0.57，偏空但未放量破位。','events':'A级安全与资金偏好风险偏空占优。','onchain':'最近3条网络正常、无大额异动，neutral/confidence 0.3，无方向确认。','sentiment_macro':f"恐惧贪婪{macro['fng']['value']}（{macro['fng']['label']}），BTC DVOL {macro['dvol_btc']['dvol']}；稳定币约{macro['stablecoins']['pegged_usd_total']/1e9:.1f}B仅为潜在流动性；movers失败（Binance 502）。",'conclusion':'未形成完整共振：技术/事件偏空，情绪谨慎，链上中性，宏观仅潜在对冲。'},'prediction':{'btc_price':64107.28,'horizon':'未来1-2小时（低置信度）','probabilities':{'上行':0.18,'下行':0.39,'震荡':0.43},'support':[64000,63800,63600],'resistance':[64190,64500,65000,65510],'scenarios':'基准64000-64190震荡；放量跌破64000看63800-63600；站回64190且量比>1后才上调反弹概率。'},'conclusion':'等待：没有强信号≥0.7且多因子共振的现货买入。BNB虽0.75但无量、横盘、逆BTC；LINK/NEO低于阈值。零持仓不执行卖出/裸空。不注册thesis、不下模拟单、不新写alert_pending，保留既有告警。','action':{'status':'wait_no_actionable_opportunity','registered_thesis':False,'risk_approved':False,'simulated_order':'not_submitted','alert_pending':'not_written_new','watch_conditions':['BNB量比>1、RSI>45并站回均线','BTC站回64190且量比>1或放量跌破64000','NEO量比>1且RSI上穿30','链上方向信号confidence>=0.6','Binance testnet/API恢复']},'data_quality':{'opportunities_updated_at':opp['opportunities']['updated_at'],'macro_updated_at':macro['updated_at'],'movers_error':movers.get('error'),'onchain_records':len(onchain),'events_records':len(events),'state_updated_at':state['updated_at'],'source':'Binance testnet/local artifacts; not real-market execution'}}
with (base/'analysis_log.jsonl').open('a',encoding='utf-8') as f: f.write(json.dumps(log,ensure_ascii=False,separators=(',',':'))+'\n')
print(json.dumps(record_usage(provider='deepseek',model='deepseek-v4-flash',input_tokens=10500,output_tokens=2400),ensure_ascii=False))
