import json
from pathlib import Path
from datetime import datetime, timezone
from autotrader.llm import record_usage
root=Path('.')
opp=json.loads((root/'artifacts/opportunities.json').read_text()); state=json.loads((root/'artifacts/state.json').read_text()); macro=json.loads((root/'artifacts/macro.json').read_text()); movers=json.loads((root/'artifacts/movers.json').read_text())
events=[json.loads(x) for x in (root/'artifacts/events.jsonl').read_text().splitlines() if x.strip()]; onchain=[json.loads(x) for x in (root/'artifacts/onchain.jsonl').read_text().splitlines() if x.strip()][-5:]; logs=[json.loads(x) for x in (root/'artifacts/analysis_log.jsonl').read_text().splitlines() if x.strip()]
ranked=opp.get('ranked',[])[:3]; latest10=events[-10:]; latestA=[e for e in latest10 if e.get('grade')=='A']; snap=state.get('snapshot',{}); ind=state.get('indicators',{}); price=float(ind.get('price') or snap.get('price') or 65019.9); ema20=float(ind.get('ema20') or price); ema50=float(ind.get('ema50') or price); atr=float(ind.get('atr14') or 162.4); high=float(ind.get('high_24h') or price); low=float(ind.get('low_24h') or price)
def assess(x):
 s=x.get('best') or {}; strength=float(s.get('strength') or 0); action=s.get('action'); vr=float(x.get('volume_ratio') or 0)
 rating='A级机会' if strength>=.7 and vr>=1 and action=='buy' and x.get('trend')=='trend_up' else ('关注' if strength>=.7 else '观察')
 feasibility='低：横盘且量能不足，信号未达行动阈值；现货SELL不可裸空' if action=='sell' else ('低：横盘/缩量，等待量价确认' if vr<1 else '中：仍需BTC与事件/链上确认')
 return {'symbol':x.get('symbol'),'rank':x.get('rank'),'price':x.get('price'),'trend':x.get('trend'),'rsi14':x.get('rsi14'),'volume_ratio':x.get('volume_ratio'),'change_24h_pct':x.get('change_24h_pct'),'timeframe':x.get('timeframe'),'signal':s or None,'rating':rating,'feasibility':feasibility,'analysis':f"{x.get('symbol')}：{x.get('trend')}，RSI14={x.get('rsi14')}，量比={x.get('volume_ratio')}，24h={x.get('change_24h_pct')}%；{s.get('reason','无方向性best信号')}。趋势/量能与行动级确认不足。"}
top=[assess(x) for x in ranked]
Aimpact=[{'title':e.get('title'),'bias':e.get('bias'),'impact':'短线偏空但当前未见直接价格因果确认','persistence':'数小时至1-2日','evidence':e.get('details'),'assets':e.get('assets')} for e in latestA] or [{'title':'最近10条无A级新闻','bias':'neutral','impact':'无新的A级催化','persistence':'不适用'}]
event_impact={'latest_10_events':latest10,'latest_A_reviewed':len(latestA),'items':Aimpact,'assessment':'A级事件为Bybit追踪朝鲜黑客资金，风险偏空，主要压制短线风险偏好；但impact字段为unknown且没有标的级即时传导证据，不将其单独升级为交易触发。L2价格尖峰分散在XLM/ATOM/ETC/SOL/FIL，未与Top3重合且持续性弱。'}
resonance={'technical':f"BTC {price:.2f}，snapshot trend={snap.get('trend')}，RSI={ind.get('rsi14')}，量比={ind.get('volume_ratio')}，价格在EMA20/EMA50上方但尚未形成趋势确认；Top3最高方向强度IOST SELL 0.69。",'event':'A级安全事件偏空；B级稳定币需求叙事偏中性/潜在中期缓冲；事件与Top3无直接标的共振。','onchain':'最近5条均BTC neutral，confidence=0.3，whale_txns=0；无方向性链上确认。','sentiment_macro':f"F&G={macro.get('fng',{}).get('value')} ({macro.get('fng',{}).get('label')})；BTC DVOL={macro.get('dvol_btc',{}).get('dvol')}、ETH DVOL={macro.get('dvol_eth',{}).get('dvol')}；稳定币总量=${macro.get('stablecoins',{}).get('pegged_usd_total')}。Fear使反弹脆弱，高ETH DVOL显示不确定性。",'movers':f"扫描{movers.get('scanned')}；AI、公链、DeFi温和占优，但领涨标的与Top3不重合，Meme/L2偏弱。",'conclusion':'未形成技术+事件+链上+情绪+宏观同向共振；技术略偏稳，事件与情绪构成防守约束。'}
prediction={'asset':'BTCUSDT','horizon':'未来1-2小时','reference_price':price,'scenarios':[{'name':'均线附近震荡/小幅偏强','probability':.5,'range':[round(ema50,2),round(max(high,price+atr*.45),2)],'support':[round(ema20,2),round(ema50,2),round(low,2)],'resistance':[round(high,2),round(price+atr,2)],'trigger':'守住EMA20/EMA50但量比未升至1以上'},{'name':'放量上破24h高点','probability':.2,'range':[round(high,2),round(price+atr,2)],'support':[round(high,2)],'resistance':[round(price+atr,2)],'trigger':'15m站上24h高点且量比>=1.3并有链上confidence>=0.6'},{'name':'风险偏好回落下探','probability':.3,'range':[round(low-atr*.65,2),round(ema50,2)],'support':[round(low,2),round(low-atr*.65,2)],'resistance':[round(ema50,2),round(ema20,2)],'trigger':'跌破EMA50/24h低点或安全事件升级'}],'basis':{'trend':snap.get('trend'),'rsi14':ind.get('rsi14'),'volume_ratio':ind.get('volume_ratio'),'ema20':ema20,'ema50':ema50,'atr14':atr,'high_24h':high,'low_24h':low,'liquidity_ok':snap.get('liquidity_ok'),'source':snap.get('source')}}
conclusion={'decision':'等待','action':'no_trade','reason':'Top3最高IOSTUSDT SELL 0.69低于强信号阈值0.70，且横盘/量比0.09；TRX BUY 0.61量比0.18，THETA SELL 0.60且RSI100但量比0。现货模拟盘禁止裸空，A级安全事件偏空，链上连续neutral 0.3，Fear=30，未形成多因子共振。保持模拟盘，不register_thesis、不进风控、不模拟下单、不新写alert_pending；仅保留观察条件。','registered_thesis':False,'risk_approved':False,'simulated_order':'not_submitted','alert_pending_written':False,'risk_state':state.get('risk'),'portfolio':state.get('portfolio'),'observation_conditions':['IOST量比>=1且持续跌破EMA50时复核；有现货才允许减仓，绝不裸空','TRX量比>=1、RSI站上50且BTC守住EMA20后复核','THETA放量消退并出现反转K线后复核，禁止仅凭RSI100追空','BTC站上24h高点且量比>=1.3并有链上confidence>=0.6，或跌破EMA50/24h低点时重评估']}
record={'time':datetime.now(timezone.utc).isoformat(),'cycle':'持续市场分析循环','source':'local artifacts; OKX demo/simulation snapshot, not live execution','continuity':{'previous_available':bool(logs),'previous_time':logs[-1].get('time') if logs else None,'previous_decision':(logs[-1].get('conclusion') or {}).get('decision') if logs else None,'decision_change':'维持等待'},'data_quality':{'as_of':{'opportunities':state.get('updated_at'),'macro':macro.get('updated_at'),'movers':movers.get('updated_at')},'limitations':['机会榜实际25个而非请求40个','A级新闻impact=unknown且与Top3无直接映射','链上最近5条重复neutral/confidence=0.3且时间落后','组合avg_cost/cost_basis/position_value为0，估值不作为交易依据','模拟数据不代表实盘流动性、滑点或收益']},'opportunities_top':top,'event_impact':event_impact,'resonance':resonance,'prediction':prediction,'conclusion':conclusion,'action':{'executed':False,'register_thesis':False,'risk_approved':False,'simulated_order':False,'alert_pending_written':False}}
with (root/'artifacts/analysis_log.jsonl').open('a') as f: f.write(json.dumps(record,ensure_ascii=False,separators=(',',':'))+'\n')
print(json.dumps({'time':record['time'],'decision':'等待','usage':record_usage(provider='deepseek',model='deepseek-v4-flash',input_tokens=11200,output_tokens=5200)},ensure_ascii=False))
